version: '2'
services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_USER=reviewboard
    memcached:
        image: memcached
    reviewboard:
        image: seanhoughton/reviewboard
        build: ./
        volumes:
            - /root/.ssh
            - /media
        depends_on:
            - postgres
            - memcached
        environment:
            - PGHOST=postgres
            - MEMCACHED=memcached:11211
            - WAIT_FOR_POSTGRES=true
        ports:
            - 8000:8000
